apiVersion: apps/v1
kind: Deployment
metadata:
  name: testDemo-k8s-deployments
spec:
  selector:
    matchLabels:
      app: testDemo-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: testDemo-k8s
    spec:
      containers:
      - name: testDemo-k8s
        image: karthikvram/testdemo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: testDemo-k8s-service
spec:
  selector:
    app: testDemo-k8s  # Fixed from testDemo_k8Service
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8081
  type: NodePort  # Keep as ClusterIP unless you want external access